/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ExampleManagerInterface extends ethers.utils.Interface {
  functions: {
    "deleteUser(bytes32)": FunctionFragment;
    "deposit(bytes32,uint256)": FunctionFragment;
    "editUser(bytes32,string,string)": FunctionFragment;
    "getAllUsers()": FunctionFragment;
    "getMyUser()": FunctionFragment;
    "getUser(bytes32)": FunctionFragment;
    "getUserByName(string)": FunctionFragment;
    "getUserByOwner(address)": FunctionFragment;
    "initToken()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "newUser(string,string)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transfer(bytes32,bytes32,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deleteUser",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "editUser",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getMyUser", values?: undefined): string;
  encodeFunctionData(functionFragment: "getUser", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getUserByName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserByOwner",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "newUser",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deleteUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "editUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Approval(bytes32,uint256)": EventFragment;
    "Deposit(bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transfer(bytes32,bytes32,uint256)": EventFragment;
    "UserCreated(bytes32,string,string)": EventFragment;
    "UserDeleted(bytes32)": EventFragment;
    "UserEdited(bytes32,string,string)": EventFragment;
    "Withdraw(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserEdited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class ExampleManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ExampleManagerInterface;

  functions: {
    deleteUser(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deleteUser(bytes32)"(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deposit(bytes32,uint256)"(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    editUser(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "editUser(bytes32,string,string)"(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllUsers(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        })[]
      ]
    >;

    "getAllUsers()"(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        })[]
      ]
    >;

    getMyUser(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    "getMyUser()"(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    getUser(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    "getUser(bytes32)"(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    getUserByName(
      _name: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    "getUserByName(string)"(
      _name: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    getUserByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    "getUserByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string, BigNumber, BigNumber] & {
          id: string;
          owner: string;
          name: string;
          password: string;
          dateCreated: BigNumber;
          dateModified: BigNumber;
        }
      ]
    >;

    initToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initToken()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newUser(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newUser(string,string)"(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transfer(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transfer(bytes32,bytes32,uint256)"(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdraw(bytes32,uint256)"(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deleteUser(
    _id: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deleteUser(bytes32)"(
    _id: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    _recipientId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deposit(bytes32,uint256)"(
    _recipientId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  editUser(
    _id: BytesLike,
    _newName: string,
    _newPass: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "editUser(bytes32,string,string)"(
    _id: BytesLike,
    _newName: string,
    _newPass: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllUsers(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    })[]
  >;

  "getAllUsers()"(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    })[]
  >;

  getMyUser(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  "getMyUser()"(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  getUser(
    _id: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  "getUser(bytes32)"(
    _id: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  getUserByName(
    _name: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  "getUserByName(string)"(
    _name: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  getUserByOwner(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  "getUserByOwner(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, BigNumber, BigNumber] & {
      id: string;
      owner: string;
      name: string;
      password: string;
      dateCreated: BigNumber;
      dateModified: BigNumber;
    }
  >;

  initToken(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initToken()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _users: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _users: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newUser(
    _name: string,
    _password: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newUser(string,string)"(
    _name: string,
    _password: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transfer(
    _spenderId: BytesLike,
    _recipientId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transfer(bytes32,bytes32,uint256)"(
    _spenderId: BytesLike,
    _recipientId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    _spenderId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdraw(bytes32,uint256)"(
    _spenderId: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deleteUser(_id: BytesLike, overrides?: CallOverrides): Promise<void>;

    "deleteUser(bytes32)"(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(bytes32,uint256)"(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    editUser(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "editUser(bytes32,string,string)"(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllUsers(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      })[]
    >;

    "getAllUsers()"(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      })[]
    >;

    getMyUser(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    "getMyUser()"(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    getUser(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    "getUser(bytes32)"(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    getUserByName(
      _name: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    "getUserByName(string)"(
      _name: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    getUserByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    "getUserByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, BigNumber, BigNumber] & {
        id: string;
        owner: string;
        name: string;
        password: string;
        dateCreated: BigNumber;
        dateModified: BigNumber;
      }
    >;

    initToken(overrides?: CallOverrides): Promise<void>;

    "initToken()"(overrides?: CallOverrides): Promise<void>;

    initialize(_users: string, overrides?: CallOverrides): Promise<void>;

    "initialize(address)"(
      _users: string,
      overrides?: CallOverrides
    ): Promise<void>;

    newUser(
      _name: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "newUser(string,string)"(
      _name: string,
      _password: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transfer(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(bytes32,bytes32,uint256)"(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(bytes32,uint256)"(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Approval(
      spender: BytesLike | null,
      amount: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { spender: string; amount: BigNumber }
    >;

    Deposit(
      recipient: BytesLike | null,
      amount: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { recipient: string; amount: BigNumber }
    >;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Transfer(
      spender: BytesLike | null,
      recipient: BytesLike | null,
      amount: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { spender: string; recipient: string; amount: BigNumber }
    >;

    UserCreated(
      id: BytesLike | null,
      name: string | null,
      password: null
    ): TypedEventFilter<
      [string, string, string],
      { id: string; name: string; password: string }
    >;

    UserDeleted(
      id: BytesLike | null
    ): TypedEventFilter<[string], { id: string }>;

    UserEdited(
      id: BytesLike | null,
      newName: string | null,
      newPassword: null
    ): TypedEventFilter<
      [string, string, string],
      { id: string; newName: string; newPassword: string }
    >;

    Withdraw(
      spender: BytesLike | null,
      amount: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { spender: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    deleteUser(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deleteUser(bytes32)"(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deposit(bytes32,uint256)"(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    editUser(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "editUser(bytes32,string,string)"(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllUsers(overrides?: CallOverrides): Promise<BigNumber>;

    "getAllUsers()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMyUser(overrides?: CallOverrides): Promise<BigNumber>;

    "getMyUser()"(overrides?: CallOverrides): Promise<BigNumber>;

    getUser(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getUser(bytes32)"(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserByName(_name: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getUserByName(string)"(
      _name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initToken()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address)"(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newUser(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newUser(string,string)"(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transfer(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transfer(bytes32,bytes32,uint256)"(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdraw(bytes32,uint256)"(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deleteUser(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deleteUser(bytes32)"(
      _id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(bytes32,uint256)"(
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    editUser(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "editUser(bytes32,string,string)"(
      _id: BytesLike,
      _newName: string,
      _newPass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAllUsers()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMyUser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMyUser()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUser(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUser(bytes32)"(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserByName(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserByName(string)"(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initToken()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _users: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newUser(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newUser(string,string)"(
      _name: string,
      _password: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transfer(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transfer(bytes32,bytes32,uint256)"(
      _spenderId: BytesLike,
      _recipientId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(bytes32,uint256)"(
      _spenderId: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
