version: "3.5"

services:
  database:
    image: mongo:latest
    container_name: erc20-example-mongo
    environment:
      - MONGO_INITDB_DATABASE=erc20-example
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/docker-volumes/mongodb:/data/db
    #command: [--auth]
    ports:
      #- "27017-27019:27017-27019"
      - "27017:27017"
    networks:
      - erc20-example-net

  erc20-example-back:
    build:
      context: .
      dockerfile: Dockerfile
    #image: node:12
    container_name: erc20-example-back
    #restart: unless-stopped
    environment:
      - NODE_ENV=production
      #- MONGO_DB_URI=mongodb://Mongo-DB:27017/paap
      #- JWT_SECRET=my_secret
    volumes:
      #- .:/usr/src/app
      #- ./node_modules:/usr/src/app/node_modules
      # ENVIRONMENT
      #- ./.env:/usr/src/app/.env
      - ./.env.development:/home/server/.env.development
      - ./.env.production:/home/server/.env.production
      #- ./src/contracts/artifacts:/home/server/src/contracts/artifacts
    ports:
      - 3000:3000
    #command: npm run start:dev
    depends_on:
      - database
      - ganache
    networks:
      - erc20-example-net

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: "ganache-cli"
    ports:
      - "8545:8545"
    volumes:
      - ~/docker-volumes/ganache:/ganache_data
    command: "--accounts 12 --secure --port 8545 --gasPrice 0 --gasLimit 9999999999999999"
    networks:
      - erc20-example-net

networks:
  erc20-example-net:
